# Generated by Django 4.1.1 on 2022-10-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.CharField(max_length=30)),
                ('front_camera', models.CharField(blank=True, max_length=100)),
                ('rear_camera', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('battery_capacity', models.CharField(blank=True, max_length=25)),
                ('sensors', models.CharField(blank=True, max_length=255)),
                ('speakers', models.CharField(blank=True, max_length=255)),
                ('Screen_resolution', models.CharField(blank=True, max_length=115)),
                ('charging', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(blank=True, max_length=60)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('memory', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('slots', models.CharField(blank=True, max_length=255)),
                ('phone_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('phone_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
