# Generated by Django 4.1.1 on 2022-09-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('company_details', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('price', models.IntegerField()),
                ('phone_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
