# Generated by Django 4.1.1 on 2022-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_phone_image_alter_product_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone_image',
            field=models.ImageField(blank=True, upload_to='img/%y'),
        ),
    ]
